# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_test_funcs": "core.ipynb",
         "print_result": "core.ipynb",
         "do": "core.ipynb",
         "Common": "mock.ipynb",
         "get_conversations": "mock.ipynb",
         "get_conversation": "mock.ipynb",
         "handle_conversation_detail": "mock.ipynb",
         "start_conversation": "mock.ipynb",
         "generate_title": "mock.ipynb",
         "rename_title": "mock.ipynb",
         "delete_conversation": "mock.ipynb",
         "recover_conversation": "mock.ipynb",
         "clear_conversations": "mock.ipynb",
         "chat_gpt_base_url": "mock.ipynb",
         "common": "mock.ipynb",
         "attrdict": "mock.ipynb",
         "attributize": "mock.ipynb",
         "delta": "mock.ipynb",
         "mock_create": "mock.ipynb",
         "chat_delta": "mock.ipynb",
         "mock_chat_create": "mock.ipynb",
         "mock_openai": "mock.ipynb"}

modules = ["__init__.py",
           "mock.py"]

doc_url = "https://seii-saintway.github.io/ipymock/"

git_url = "https://github.com/seii-saintway/ipymock/tree/main/"

def custom_doc_links(name): return None
