# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_test_funcs": "1_core.ipynb",
         "print_result": "1_core.ipynb",
         "do": "1_core.ipynb",
         "Common": "2_browser.ipynb",
         "common": "4_agi.ipynb",
         "get_conversations": "2_browser.ipynb",
         "get_conversation": "2_browser.ipynb",
         "handle_conversation_detail": "2_browser.ipynb",
         "start_conversation": "2_browser.ipynb",
         "generate_title": "2_browser.ipynb",
         "rename_title": "2_browser.ipynb",
         "delete_conversation": "2_browser.ipynb",
         "recover_conversation": "2_browser.ipynb",
         "clear_conversations": "2_browser.ipynb",
         "attrdict": "2_browser.ipynb",
         "attributize": "2_browser.ipynb",
         "delta": "2_browser.ipynb",
         "mock_create": "3_llm.ipynb",
         "chat_delta": "2_browser.ipynb",
         "mock_chat_create": "2_browser.ipynb",
         "mock_openai": "2_browser.ipynb",
         "embeddings_model": "4_agi.ipynb",
         "mock_openai_embed": "3_llm.ipynb",
         "embedding_size": "4_agi.ipynb",
         "index": "4_agi.ipynb",
         "vectorstore": "4_agi.ipynb",
         "TaskCreationChain": "4_agi.ipynb",
         "TaskPrioritizationChain": "4_agi.ipynb",
         "ExecutionChain": "4_agi.ipynb",
         "get_next_task": "4_agi.ipynb",
         "prioritize_tasks": "4_agi.ipynb",
         "get_top_tasks": "4_agi.ipynb",
         "execute_task": "4_agi.ipynb",
         "BabyAGI": "4_agi.ipynb",
         "tools": "4_agi.ipynb",
         "ZeroRoundAgent": "4_agi.ipynb",
         "llm": "4_agi.ipynb",
         "FORMAT_INSTRUCTIONS": "4_agi.ipynb",
         "llm_chain": "4_agi.ipynb",
         "ChineseOutputParser": "4_agi.ipynb",
         "FINAL_ANSWER_ACTION": "4_agi.ipynb",
         "agent_executor": "4_agi.ipynb",
         "baby_agi": "4_agi.ipynb",
         "final_objective": "4_agi.ipynb",
         "test_baby_agi": "4_agi.ipynb",
         "mock_baby_agi": "4_agi.ipynb",
         "DuckDuckGoSearchAPIWrapper": "4_tools_duckduckgo.ipynb"}

modules = ["__init__.py",
           "browser.py",
           "llm.py",
           "agi.py",
           "reader.py"]

doc_url = "https://seii-saintway.github.io/ipymock/"

git_url = "https://github.com/seii-saintway/ipymock/tree/main/"

def custom_doc_links(name): return None
