# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_test_funcs": "core.ipynb",
         "print_result": "core.ipynb",
         "do": "core.ipynb"}

modules = ["__init__.py"]

doc_url = "https://seii-saintway.github.io/ipytest/"

git_url = "https://github.com/seii-saintway/ipytest/tree/main/"

def custom_doc_links(name): return None
